### ISSUE TITLE
[Q] is fairy concerned by sketching deserts ?

### ISSUE THREAD

**Issue by Louis-MG** [bluenote-1577/fairy#7]
Hello ! Thank for the work you've done, it i going to save a lot of time ! 

I recently read '_k_-nonical space: sketching with reverse complement' [Oxford bioinformatics](https://academic.oup.com/bioinformatics/article/40/11/btae629/7829143?login=false). My understanding is that region of genomes may be ignored by context-free sketching methods, and that _hash-based_ methods are context-free. Fairy is based on FracMinHash, which uses hash, therefore is a context free method.

My question is: it seems that fairy might be subject to that problem, do you agree or is there a nuance of difference that prevents sketching deserts ? The results of fairy are very promising but I would like to know about this potential caveat !

**Comment by bluenote-1577** [comment]
hi @Louis-MG 

this is an interesting question. i haven't done testing on sketching deserts. in practice, I found that for larger contigs, fracminhash is sufficient... perhaps a better k-mer sketching algorithm would improve fairy on smaller contigs.

I'll close this issue since this is the subject of a larger investigation. Thanks for bringing this up though!
